import os
from lupa.lua51 import LuaRuntime
lua = LuaRuntime(unpack_returned_tuples=True)

data_path = "Contents/mods/HorseMod/42/media/lua/shared/HorseMod/attachments/AttachmentData.lua"

with open(os.path.abspath(data_path), 'r') as file:
    attachment_data = file.read()

# execute the file and cache the returned data table
AttachmentsData = lua.execute(attachment_data)

DEFAULT_PAGE = """.. THAT PAGE IS AUTOGENERATED WITH A PYTHON SCRIPT - DO NOT EDIT MANUALLY!

SlotDefinition
==============

.. lua:autoclass:: HorseMod.SlotDefinition
    :members:

.. _availableslots-label:

Slots available
---------------
Below is a list of all the available slots in the Horse mod defined in :lua:obj:`HorseMod.attachments.AttachmentData.slotsDefinitions`.

{data}
"""

MAPPING = ":lua:obj:`{key} <HorseMod.SlotDefinition.{key}>`"

# MAPPING = {
#     "modelAttachment": ":lua:obj:`HorseMod.SlotDefinition.modelAttachment`",
#     "isMane": ":lua:obj:`isMane <HorseMod.SlotDefinition.isMane>`",
#     "defaultMane": ":lua:obj:`HorseMod.SlotDefinition.defaultMane`",
# }

slotsDefinitions = [(slot, definition) for slot, definition in AttachmentsData.slotsDefinitions.items()]
slotsDefinitions = sorted(slotsDefinitions, key=lambda x: x[0])

data = ""
for slot, definition in slotsDefinitions:
    data += f"{slot}"
    
    for key, value in definition.items():
        data += f"\n  {MAPPING.format(key=key)} = ``{value}``\n"

    data += "\n"

with open("docs/source/classes/SlotDefinition.rst", 'w') as file:
    file.write(DEFAULT_PAGE.format(data=data))